# Generated by Django 4.2.6 on 2023-12-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_enrollment_alter_student_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='courses',
            new_name='courses_new',
        ),
    ]
